language: cpp
addons:
  apt:
    packages:
      - doxygen
before_script:
  - sudo apt-get install libboost-test-dev -y
  - echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
script:
  - cmake .
  - cmake --build .
  - cmake --build . --target test
  - cmake --build . --target package
  - doxygen $TRAVIS_BUILD_DIR/Doxyfile
deploy:
  provider: script
  skip_cleanup: true
  script:
    - curl -T sketch-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uromanovaangelina:$BINTRAY_API_KEY "https://api.bintray.com/content/romanovaangelina/OTUS/HW-4/$TRAVIS_BUILD_NUMBER/sketch-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"