language: cpp
addons:
  apt:
    packages:
      - libboost-test-dev
script:
  - cmake .
  - cmake --build .
  - cmake --build . --target package
  - test/project_test
deploy:
  provider: script
  skip_cleanup: true
  script:
    - curl -T matrix-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uromanovaangelina:$BINTRAY_API_KEY "https://api.bintray.com/content/romanovaangelina/OTUS/HW-5/$TRAVIS_BUILD_NUMBER/matrix-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
  on:
    all_branches: true